name: Commit
on: push
jobs:
  commit_lint:
    name: Commit Lint
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node v20
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm install -g @commitlint/config-conventional@18.6.0 @commitlint/cli@18.6.0
      - run: |
          CONFIG_COMMITLINT=$(cat << JSON
            {
              "extends": [
                "@commitlint/config-conventional"
              ]
            }
          JSON
          )
          echo $CONFIG_COMMITLINT > .commitlintrc.json
      - run: git log --pretty=format:"%s" $(git describe --tags --abbrev=0 @^)..@ | while read line; do echo "$line" | commitlint; done
  code_lint:
    name: Code Lint
    continue-on-error: true
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          distribution: 'oracle'
          java-version: 18
      - run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.3.1/ktlint && chmod a+x ktlint
      - name: Run ktlint (Android)
        run: |
          ./ktlint -F "**/src/**/*.kt" "!**/generated/**" --reporter=plain?group_by_file
  unit_tests:
    name: Unit Tests
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          distribution: 'oracle'
          java-version: 18
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: gradle/gradle-build-action@v2.3.3
      - name: Execute Gradle build
        run: ./gradlew test
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          distribution: 'oracle'
          java-version: 18
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build Library
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: assemble